
all:
	gcc -I/home/obp/cipt/graphviz-install/include -I/home/obp/cipt/graphviz-install/include/graphviz -I/home/obp/cipt/graphviz/lib/common -I/usrs/include -std=c99 -L/usr/lib -lcairo -lm -L/home/obp/cipt/graphviz-install/lib -lsfdp -o sfdp-lite ./lib/mmio/mmio.c -g main.c

clean:
	rm -rf sfdp-lite

